name: Review PR with LLM

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          pip3 install requests

      - name: Analyze PR with LLM
        run: python3 review_pr.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
