name: Review PR with LLM

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch master branch
        run: git fetch origin master:master

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Analyze PR with LLM
        run: python review_pr.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
